//change flash url because the url is generated by script.
//app engine can't replace this absoluted url with a relative url

var youtubetimeid = 0;

function youtubetimercallback()
{
    console.log("youtubetimercallback");
    clearInterval(youtubetimeid);
    var flashEle = document.getElementsByTagName("embed")[0];
    var absolutedUrl = flashEle.src;
    console.log(absolutedUrl);
    var relativeurl = absolutedUrl.replace("http://", "/");
    console.log(relativeurl);
    flashEle.src = relativeurl;
}
youtubetimeid = setInterval(youtubetimercallback, 2000);
