/*global window, console, document, chrome*/
//change flash url because the url is generated by script.
//app engine can't replace this absoluted url with a relative url

(function () {
    var youtubetimeid, youtubetimercallback;

    youtubetimercallback = function () {
        var flashEle, absolutedUrl, relativeurl;
        console.log("youtubetimercallback");
        window.clearInterval(youtubetimeid);
        flashEle = document.getElementsByTagName("embed")[0];
        absolutedUrl = flashEle.src;
        console.log(absolutedUrl);
        relativeurl = absolutedUrl.replace("http://", "/");
        console.log(relativeurl);
        flashEle.src = relativeurl;
    };
    youtubetimeid = window.setInterval(youtubetimercallback, 2000);
}());
